config/routes.rb
Blog::Application.routes.draw do

match '/posts' => 'posts#index', :as => :posts, :via => :get
match '/posts/new' => 'posts#new', :as => :new_post, :via => :get
match '/posts' => 'posts#create', :via => :post
match '/posts/:id/edit' => 'posts#edit', :as => :edit_post, :via => :get
match '/posts/:id' => 'posts#update', :via => :put
match '/posts/:id' => 'posts#show', :as => :show_post, :via => :get
match '/posts/:id' => 'posts#delete', :as => :delete_post, :via => :delete
match '/posts/:post_id/comments' => 'comments#create', :via => :post
match '/posts/:post_id/comments/:id' => 'comments#delete', :as => :delete_comment, :via => :delete
match '/posts/search' => 'posts#search', :via => :post
match '/session/new' => 'session#new', :as => :new_session, :via => :get
match '/session' => 'session#create', :via => :get
match '/session' => 'session#delete', :as => :delete_session, :via => :delete
match '/contact/create' => 'contact#create', :via => :post

  root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :name, :presence => true
  validates :content, :presence => true
end

app/models/post.rb
require 'bb-ruby'
class Post < ActiveRecord::Base
  has_many :comments, :dependent => :delete_all
  has_and_belongs_to_many :tags
  
  def printBody
    body.bbcode_to_html_with_formatting.html_safe
  end
  
  
  def printDescription
    if body.length <= 300
      body.bbcode_to_html_with_formatting.html_safe
    else
      text="#{body[0..299]} ..."
      text.bbcode_to_html_with_formatting.html_safe
    end
  end
  
  def bodyWithoutBbcode
    body.gsub(/\[[a-zA-z09=_\/:,\.-]*\]/,"")
  end
  
  
  def addTag(tags)
    tags=tags.split(',').map do |tag|
      tag=Tag.find_or_create_by_name(tag)
    end
    self.tags << tags
  end
  
  def getTag
    self.tags.map{ |t| t.name}.join(", ")
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  protect_from_forgery
  #include SessionHelper
  
   def current_user
    @current_user = session["current_user"]
  end
  
   def is_connected?
    !session["current_user"].nil?
  end
  
  
  def need_to_be_connected
      session["source"]=request.fullpath
      redirect_to(new_session_path) unless is_connected?
  end
  
  
  
  private
    if Rails.env.test?
      before_filter :stub_current_user
      def stub_current_user
        session["current_user"]= cookies[:stub_session] if cookies[:stub_session]
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   before_filter :need_to_be_connected, :only => :delete
  def create
    @post = Post.find_by_id(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    if @comment.valid?
      respond_to do |format|
          format.html { redirect_to show_post_path(@post)}
          format.json { render json: @comment}
          format.js
      end
      else
        flash[:error]="Comment Fields must not be empty !"
        respond_to do |format|
          format.html { render "posts/show"}
          format.js   { render "comments/error"}
        end
     end
  end
  
  
  def delete
    p = Post.find_by_id(params[:post_id])
    @comment = p.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
        format.html { redirect_to show_post_path(p)}
        format.json { render json: @comment}
        format.js
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ActionController::Base
  def create
    ContactMeMailer.contact(params[:contact][:name],params[:contact][:mail],params[:contact][:content]).deliver
    flash[:msg] = "Thanks i will read it as soon as possible :)"
    redirect_to "/"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :need_to_be_connected, :except => [:index, :show, :search]
  def index
    @posts = Post.paginate(:page => params[:page],:per_page=> 3).order('id DESC')
    @posts_rss=Post.all
    respond_to do |format|
      format.html
      format.rss { render :layout => false}
      format.json { render json: @posts }
    end
  end
  
  def new
    @post = Post.new
  end
 
  def create
    @post = Post.new(params[:post])
    @post.save
    @post.addTag(params[:tags][:name])
    flash[:msg] = "Post was created with success :) !"
    #redirect_to()
    respond_to do |format|
        format.html { redirect_to posts_path}
        format.json { render json: @post}
        format.js
    end
  end
  
  def edit
    @post = Post.find_by_id(params[:id])
     respond_to do |format|
        format.html
        format.json { render json: @post}
        format.js
    end
  end
  
  def update
    @post = Post.find_by_id(params[:id])
    @post.update_attributes(params[:post])
    @post.tags.clear
    @post.addTag(params[:tags][:name])
    flash[:msg] = "Post was updated with success :) !"
    #redirect_to(posts_path)
     respond_to do |format|
        format.html { redirect_to posts_path}
        format.json { render json: @post}
        format.js
    end
  end
  
  def show
    @post = Post.find_by_id(params[:id])
  end
  
  def delete
    @post = Post.find_by_id(params[:id])
    @post.destroy
    #redirect_to(posts_path)
    respond_to do |format|
        format.html { redirect_to posts_path}
        format.json { render json: @post}
        format.js
    end
  end
  
  def search
    val=params[:search]
    @posts = Post.find(:all,:conditions=> [ "title LIKE ? OR body LIKE ?", "%#{val}%","%#{val}%" ]) 
    flash[:search] = "No posts found. Try a different search ?" if @posts.empty?
    render :index
  end
  
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    include SessionHelper
  def new
      session["source"] = params["src"] if params["src"]
      redirect_to("http://sauth:4567/lokhilabs/session/new?origin=/session&amp;secret=blog")
  end
  
  def create
    key=File.read(Rails.root.join('app/assets/private.pem'))
    session["current_user"] = decypher(key,params["login"])
    redirect_to (session["source"] || root_path)
  end
  
  def delete
    session["current_user"] = nil
    cookies[:stub_session] = nil if Rails.env.test?
    redirect_to posts_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
  require 'openssl'
  require 'base64'
 
  def decypher(key,elogin)
    clogin=Base64.urlsafe_decode64(elogin)
    privkey=OpenSSL::PKey::RSA.new(key)
    login=privkey.private_decrypt(clogin)
  end
end

app/views/comments/_form_comment.html.erb
<div class="form">
 <% if flash[:error] %>
    <div class="flash-error">
      <%= flash[:error] %>
    </div>
  <% end %>
<p>Add your comment </p>
<%= form_tag("/posts/#{@post.id}/comments", :method => "post",:remote => true) do %>
<%= label(:comment,:name, "name :") %>
<% if current_user %>
<%= text_field(:comment, :name, :size => 55,:class => "form-field",:value => current_user) %>
<% else %>
<%= text_field(:comment, :name, :size => 55,:class => "form-field") %>
<% end %>
<br /><br />
<%= label(:comment,:content, "content :", :id => "labelarea") %>
<%= text_area(:comment, :content, :size => "55x10", :class => "form-field") %>
<br />
<p class="end"></p>
<%= submit_tag("Add the comment", :class => "form-submit") %>
<% end %>
</div>

app/views/comments/_last_comments.html.erb
<div class="last">
  <p>Latest Comments</p>
  <ul>
    <% Comment.order("id desc").limit(5).each do |comment| %> 
    <li>
      <%= link_to comment.content[0..50]+"...",show_post_path(comment.post_id)+"#comment_#{comment.id}" %>
    </li>
    <% end %>
  </ul>
</div>

app/views/comments/_listing_comment.html.erb
<div class="listing-comments" id="comments">
  <ul>
  <% @post.comments.all.each do |comment| %> 
    <li id="comment_<%= comment.id %>">
       <p class="comment-name"><%= comment.name %><span> <%= comment.created_at %></span></p>
      <p class="comment-content" ><%= comment.content %></p>
      <% if current_user %><p><%= link_to 'Delete',delete_comment_path(@post.id,comment.id), method: :delete, :remote => true %> </p><% end %>
    </li>
  <% end %>
  </ul>
</div>

app/views/comments/create.js.erb
$("div.flash-error").remove();
$("body .listing-comments ul").append('<li id="comment_<%= @comment.id %>" ><p class="comment-name"><%= escape_javascript(@comment.name) %><span> <%= @comment.created_at %></span></p> <p class="comment-content" ><%= escape_javascript(@comment.content) %></p><p><%= escape_javascript(link_to 'Delete',delete_comment_path(@comment.post_id,@comment.id), method: :delete, :remote => true) %></p></li>');
$('div.last p:contains("Latest Comments")').parent().children('ul').prepend('<li><%= escape_javascript(link_to @comment.content[0..50]+"...",show_post_path(@comment.post_id)+"#comment_#{@comment.id}") %></li>');
$("div.form form").children(':input').not(':submit').val('');

app/views/comments/delete.js.erb
$('li#comment_<%= @comment.id %>').remove();
$('div.last ul li a[href="<%= "#{show_post_path(@comment.post_id)}#comment_#{@comment.id}" %>"]').parent().remove();

app/views/comments/error.js.erb
$("div.flash-error").remove();
$("div.form").prepend('<% if flash[:error] %><div class="flash-error"><%= flash[:error] %></div><% end %>');

app/views/contact/_contact.html.erb
<h4>Contact me</h4>
<form action="/contact/create" method="post" id="contact">
		<input type="text" id="name" name="contact[name]" placeholder="Name"  /><br />
		<input type="text" id="mail" name="contact[mail]" placeholder="Email" /><br />
		<textarea id="content" name="contact[content]" ></textarea><br />
    <input type="submit" id="send" value="Send"  />
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) || "LokhiLabs" %></title>
    <%= stylesheet_link_tag    "style", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <meta charset="utf-8" />
    <%= csrf_meta_tags %>
  </head>
  <body id="top">
   <div class="header">
    <div class="header-box">
      <div class="logo">
        <%= link_to image_tag("logo.png", :alt => "Lokhi Labs"), posts_path, :title => "homepage" %>
      </div>
    </div>
  </div>
  <div class="content">
    <div class="content-left">
      <%= yield %>
    </div>
    <div class="content-right">
    <%= render 'posts/search_posts' %>
    
    <div class="pres">
      <div class="pres-avatar">
         <%= image_tag "pirate.png" , :alt => "Pirate" %>
      </div>
      <div class="pres-content">
        <p>Bienvenue sur mon blog !</p>
        <br />
        <p>Je suis Lokhi une jeu apprenti ingénieur en informatique et réseaux. Je vis entre la Côte d'Azur et Toulouse, je parle dans ce blog de divers sujets, informatique, sécurité, musique, mode, bref tout ce qui me passione :)</p>
      </div>
      <p class="end"></p>
    </div>
    <%= render 'session/session' %>
    <%= render 'posts/last_posts' %>
    <%= render 'comments/last_comments' %>
    <%= link_to image_tag("rss.png", :alt => "rss"), posts_path(:rss), :title => "RSS"  %>


    </div>
  </div>
  <p class="end"></p>
  <div class="footer">
    <div class="footer-box">
      <div class="footerTotop">
         <%= link_to image_tag("top.png", :alt => "Go the top"),"#top", :title => "Top"  %>
      </div>
      <div class="footercontent">
       Ce blog à été codé en Ruby On Rails, vous pouvez voir le code source sur GitHub si vous voyez une faille, ou me proposer une meilleur façon de coder ce que j'ai fait contactez moi :)<br /><br />
        <%= link_to image_tag("github.png", :alt => "GitHub"), "http://github.com/lokhi", :title => "Check me out on GitHub" %>
      </div>
      <div class="footer-bulle">
      <div class="bullecontent">
        <%= render 'contact/contact' %>
      </div>
    </div>
    </div>
  </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="form">
  <p>Create a new post</p>
  <%= form_tag("/posts",:id => "new_post" ,:method => "post",:remote =>"true") do %>
  <%= label(:post,:title, "title :") %>
  <%= text_field(:post, :title, :size => 55,:class => "form-field") %>
  <br /><br />
  <%= label(:post,:body, "content :", :id => "labelarea") %>
  <%= text_area(:post, :body,:size => "55x10", :class => "form-field") %>
  <p class="end"></p> <br />
  <%= label(:tags,:name, "tags :") %>
  <%= text_field(:tags,:name, :size => 55,:class => "form-field") %>
  <br /> 
  <%= submit_tag("New Post",:class => "form-submit") %>
  <% end %>
</div>

app/views/posts/_formEdit.html.erb
<div class="form">
  <p>Edit the post</p>
  <%= form_tag("/posts/#{@post.id}",:method => "put",:remote =>"true") do %>
  <%= label(:post,:title, "title :") %>
  <%= text_field(:post, :title, :size => 55,:class => "form-field") %>
  <br /><br />
  <%= label(:post,:body, "content :", :id => "labelarea") %>
  <%= text_area(:post, :body,:size => "55x10", :class => "form-field") %>
  <p class="end"></p><br />
  <%= label(:tags,:name, "tags :") %>
  <%= text_field(:tags,:name, :size => 55,:class => "form-field",:value=>@post.getTag) %>
  <br />
  <%= submit_tag("Update the Post",:class => "form-submit") %>
  <% end %>
</div>

app/views/posts/_last_posts.html.erb
<div class="last">
  <p>Latest Posts</p>
  <ul>
    <% Post.order("id desc").limit(5).each do |post| %> 
    <li>
    <%= link_to post.title,show_post_path(post.id)%>
    </li>
    <% end %>
  </ul>
</div>

app/views/posts/_search_posts.html.erb
<div class="search">
  <form method="post" action="/posts/search">
    <input class="searchfield" name="search" type="text" placeholder="Search"/>
    <input type="submit" class="loupe" id="Search" value="" />
  </form>
</div>

app/views/posts/create.js.erb
$("body .list-posts ul").prepend('<li class="post"><div class="post-title"><h1 class="post-title"><%= escape_javascript(link_to @post.title,show_post_path(@post.id)) %></h1><span class="adminlink"><%= escape_javascript(link_to 'Edit', edit_post_path(@post),:remote => true) %> | <%= escape_javascript(link_to 'Delete', delete_post_path(@post),  method: :delete, :remote => true) %></span><h3 class="post-tag"><%= escape_javascript(@post.getTag) %></h3><p class="post-date"><%= @post.created_at %></p></div><div class="post-img-comment"><%= escape_javascript(link_to @post.comments.count(), show_post_path(@post.id)+"#comments") %></div><p class="end"></p><div class="post-body"><%= escape_javascript(@post.printDescription) %></div><div class="post-read"><%= escape_javascript(link_to 'Show', show_post_path(@post)) %></div><p class="end"></p></li>');
$("div.form").remove();
$("a[href='<%= new_post_path %>']").fadeIn();
$('div.last p:contains("Latest Posts")').parent().children('ul').prepend('<li><%= escape_javascript(link_to @post.title, show_post_path(@post)) %></li>')

app/views/posts/delete.js.erb
$('div.post-read a[href="<%= show_post_path(@post.id) %>"]').parent().parent().remove();
$('div.last ul li a[href="<%= show_post_path(@post.id) %>"]').parent().remove();

app/views/posts/edit.html.erb
<div class="form">
<p>Edit the post</p>
<%= form_tag("/posts/#{@post.id}", :method => "put") do %>
<%= label(:post,:title, "title :") %>
<%= text_field(:post, :title, :size => 55,:class => "form-field") %>
<br /><br />
<%= label(:post,:body, "content :", :id => "labelarea") %>
<%= text_area(:post, :body,:size => "55x10", :class => "form-field") %>
<p class="end"></p><br />
<%= label(:tags,:name, "tags :") %>
<%= text_field(:tags,:name, :size => 55,:class => "form-field",:value=>@post.getTag) %>
<br />
<%= submit_tag("Update the Post",:class => "form-submit") %>
<% end %>
</div>
<div class="backlink">
  <p><%= link_to 'Back to home',posts_path %></p>
</div>

app/views/posts/edit.js.erb
$('div.post-read a[href="<%= show_post_path(@post.id) %>"]').parent().parent().replaceWith("<%= escape_javascript(render 'formEdit') %>")

app/views/posts/index.html.erb
<div class="list-posts">
  <% if flash[:msg] %>
    <div class="flash-msg">
      <%= flash[:msg] %>
    </div>
  <% end %>
  <% if flash[:search] %>
    <div class="search-msg">
      <p>
        <%= flash[:search] %>
     </p>
    </div>
  <% end %>
  <ul>
  <% @posts.each do |post| %> 
  <li class="post">
    <div class="post-title">
      <h1 class="post-title"> <%= link_to post.title,show_post_path(post.id)%></h1><span class="adminlink"><% if current_user %><%= link_to 'Edit',edit_post_path(post.id),:remote => true%>  |  <%= link_to 'Delete',delete_post_path(post.id), method: :delete,:remote => true %> </span><% end %>
      <h3 class="post-tag"><%= post.getTag %></h3>
      <p class="post-date"><%= post.created_at %></p>
    </div>
    <div class="post-img-comment"><%= link_to post.comments.count(), show_post_path(post.id)+"#comments" %></div>
    <p class="end"></p>
    <div class="post-body">
      <%= post.printDescription %>
    </div>
     <div class="post-read"><%= link_to 'Show',show_post_path(post.id)%></div>
     <p class="end"></p>
  </li>
  <% end %>
  </ul>
  <%  if !(request.fullpath == "/posts/search") %>
  <%= will_paginate @posts %>
  <% end %>
  <% if current_user %><p class="newpostlink"><%= link_to 'New Post', new_post_path,:remote => true %></p><% end %>
</div>

app/views/posts/new.html.erb
<div class="form">
<p>Create a new post</p>
<%= form_tag("/posts", :method => "post") do %>
<%= label(:post,:title, "title :") %>
<%= text_field(:post, :title, :size => 55,:class => "form-field") %>
<br /><br />
<%= label(:post,:body, "content :", :id => "labelarea") %>
<%= text_area(:post, :body,:size => "55x10", :class => "form-field") %>
<p class="end"></p><br />
<%= label(:tags,:name, "tags :") %>
<%= text_field(:tags,:name, :size => 55,:class => "form-field") %>
<br />
<%= submit_tag("New Post",:class => "form-submit") %>
<% end %>
</div>
<div class="backlink">
  <p><%= link_to 'Back to home',posts_path %></p>
</div>

app/views/posts/new.js.erb
$("a[href='<%= new_post_path %>']").after("<%= escape_javascript(render 'form') %>");
$("form#new_post").attr("data-remote", true);
$("a[href='<%= new_post_path %>']").fadeOut();

app/views/posts/show.html.erb
<% content_for(:title){@post.title+" | LokhiLabs"} %>

<div class="post">
  <div class="post-title">
    <h1 class="post-title"><%= @post.title %></h1>
    <h3 class="post-tag"><%= @post.getTag %></h3>
    <p class="post-date"><%= @post.created_at %></p>
  </div>
  <div class="post-img-comment"><%= link_to @post.comments.count(), show_post_path(@post.id)+"#comments" %></div>
  <p class="end"></p>
  <div class="post-body">
    <%= @post.printBody %>
  </div>
</div>
<%= render 'comments/listing_comment' %>
<%= render 'comments/form_comment' %>

app/views/posts/update.js.erb
$('div.form form').parent().replaceWith('<li class="post"><div class="post-title"><h1 class="post-title"><%= escape_javascript(link_to @post.title,show_post_path(@post.id)) %></h1><span class="adminlink"><%= escape_javascript(link_to 'Edit', edit_post_path(@post),:remote => true) %> | <%= escape_javascript(link_to 'Delete', delete_post_path(@post),  method: :delete, :remote => true) %></span><h3 class="post-tag"><%= escape_javascript(@post.getTag) %></h3><p class="post-date"><%= @post.created_at %></p></div><div class="post-img-comment"><%= escape_javascript(link_to @post.comments.count(), show_post_path(@post.id)+"#comments") %></div><p class="end"></p><div class="post-body"><%= escape_javascript(@post.printDescription) %></div><div class="post-read"><%= escape_javascript(link_to 'Show', show_post_path(@post)) %></div><p class="end"></p></li>');
$('div.last ul li a[href="<%= show_post_path(@post.id) %>"]').parent().replaceWith('<li><%= escape_javascript(link_to @post.title, show_post_path(@post)) %></li>')

app/views/session/_session.html.erb
<div class="session">
  <p class="titreSession">Session</p>
  <p class="contentSession">
    <% if current_user %>
        You are <%= current_user %> | <%= link_to "Disconnect", delete_session_path, method: :delete %> 
	    <% else %>
	      <%= link_to 'Login', new_session_path+"?src="+request.fullpath %>
    <% end %>
  </p>
</div>